name: soberpath_app
description: A comprehensive sobriety support app for recovery journey
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Date/Time Handling
  intl: ^0.18.1
  
  # Charts and Visualization
  fl_chart: ^0.64.0
  
  # Icons
  font_awesome_flutter: ^10.6.0
  
  # HTTP Requests and URL Launching
  http: ^1.1.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true